#
# WEBSITE INFORMATION
#

# Website information
title: Kelly Snider Consulting
url: "https://kellysniderconsulting.netlify.com"

#
# BUILD CONFIGURATION
#

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-seo-tag
  - html-proofer
  - jekyll-email-protect
future: true
include: ["_headers"]
