backend:
  name: "git-gateway"
media_folder: "/assets"
collections:
  #
  # Settings
  #
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      # Navbar
      - name: "navigation"
        label: "Navigation Bar"
        file: "_data/navigation.yml"
        description: "The contact button is built-in"
        fields:
          # Links in navbar
          - name: "items"
            label: "Items"
            label_singular: "Item"
            widget: list
            fields:
              # Display name
              - label: "Title"
                name: "title"
                widget: "string"

              # Target URL
              - label: "URL"
                name: "url"
                widget: "string"

      - name: "settings"
        label: "Site Settings"
        file: "_data/settings.yml"
        fields:
          # Email used in navbar
          - name: "contactEmail"
            label: "Contact Email"
            widget: string

          # Color used in navbar, 404 pages, and the title
          - label: "Color"
            name: "color"
            widget: "select"
            options:
              - { label: "Primary", value: "primary" }
              - { label: "Red", value: "danger" }
              - { label: "White", value: "light" }
              - { label: "Black", value: "dark" }
              - { label: "Blue", value: "link" }
              - { label: "Cyan", value: "info" }
              - { label: "Green", value: "success" }
              - { label: "Yellow", value: "warning" }

          # Logo URL of image stored on site
          - label: "Brand Text"
            name: "brand"
            widget: "string"

          # Deal sheet PDF
          - label: "Deal Sheet PDF"
            name: "dealSheet"
            widget: "file"
            default: "/assets/deal-sheet.pdf"

          # Picture
          - label: "Home Page Picture"
            name: "picture"
            widget: "image"
   
  #
  # Pages
  #
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    delete: false
    files:
        # Featured projects
        - label: "Featured projects"
          name: "featuredprojects"
          file: "featuredprojects.md"
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
              default: "Featured Projects"

            - label: "Layout"
              name: "layout"
              widget: "hidden"
              default: "projects"

            - label: "Project Rows"
              label_singular: "Row"
              name: "rows"
              widget: "list"
              fields:
                - label: "Projects"
                  label_singular: "Project"
                  name: "projects"
                  widget: "list"
                  fields:
                    - label: "Name"
                      name: "name"
                      widget: "string"
                    
                    - label: "Description"
                      name: "description"
                      widget: "markdown"

        # Clients
        - label: "Clients"
          name: "clients"
          file: "clients.md"
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
              default: "Clients"

            - label: "Layout"
              name: "layout"
              widget: "hidden"
              default: "clients"

            - label: "Content"
              name: "body"
              widget: "markdown"

        - label : "Home Page"
          name: "home"
          file: "index.md"
          fields:
            # Jekyll layout
            - label: "Layout"
              name: "layout"
              widget: "hidden"
              default: "home"

            # Title
            - label: "Title"
              name: "title"
              widget: "string"

            # Subtitle  
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"

            # About me
            - label: "About me"
              name: "aboutMe"
              widget: "object"
              fields:
                - label: "Text"
                  name: "text"
                  widget: "markdown"

                - label: "Color"
                  name: "color"
                  widget: "select"
                  options:
                    - { label: "Primary", value: "primary" }
                    - { label: "Red", value: "danger" }
                    - { label: "White", value: "light" }
                    - { label: "Black", value: "dark" }
                    - { label: "Blue", value: "link" }
                    - { label: "Cyan", value: "info" }
                    - { label: "Green", value: "success" }
                    - { label: "Yellow", value: "warning" }
